version: '3.9'
services:
  provider1-backend:
    hostname: backend.parkingprovider1.com
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ../parkingprovider1.env
    volumes:
      - ../cryptos1:/app/cryptos
    networks:
      - test

  provider2-backend:
    hostname: backend.parkingprovider2.com
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - ../parkingprovider2.env
    volumes:
      - ../cryptos2:/app/cryptos
    networks:
      - test

networks:
  test:
    name: fabric_test
